### ISSUE TITLE
Two launcher icons

### ISSUE THREAD

**Issue by neopraveen** [Neno0o/Uber-Android-SDK#1]
After Using uber-android sdk, I am getting  one more launcher icon. Please verify.

**Comment by Neno0o** [comment]
The library doesn't have a launcher, what launcher icon is it?

**Comment by neopraveen** [comment]
The same launcher icon I am using for my project.

**Comment by neopraveen** [comment]
Hi Neno0o Please help, I am just putting single gradle line in build.gradle and it result two same laucher icons, with same name.
compile 'com.neno0o.ubersdk:ubersdk:0.1'
I got the bug,
In library's  manifest their is a launcher activity defined.

<activity
            android:name="com.neno0o.ubersdk.Activites.Authentication"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

```
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
```

Kindly resolve it.

**Comment by Neno0o** [comment]
Sorry Neo for experiencing a bug, I'm working on it.

**Comment by Neno0o** [comment]
Hi Neo,
Compile the new version:  

``` groovy
compile 'com.neno0o.ubersdk:ubersdk:0.2'
```

Add this to your app manifest

``` xml
<activity android:name="com.neno0o.ubersdk.Activites.Authentication" />
```

Keep me posted, thanks!

**Comment by neopraveen** [comment]
Yes, now It is working fine, Thanks dear :+1:
